### ISSUE TITLE
Combined TownyAdvanced/Citizens2 Support

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-RPGBank#10]
It would be awesome if TownyAdvanced Mayors could have the ability to Spawn a maximum of 1 preset Bank NPC in their town.

A player permission to spawn/delete a BankNPC
A player command to spawn/delete a BankNPC
A config setting to set the maximum npc spawn amount a player can spawn
Ability in the Config to set the default Towny BankNPC i.e. skin, command using Citizens2

But they must have `towny.command.plot.*` to also spawn the NPC. So RPGBank checks that the player has this all the perms.

**Describe alternatives you've considered**
There's no alternatives.

**Comment by LoneDev6** [comment]
This might be a bit complicated since I don't know if they have an API structured enough to catch all the events I need to implement that

**Comment by SirCraftypants** [comment]
You already have the spawn npc bank implemented correct?

It would just be a case of creating a permission to allow a player to spawn the npc and include the `towny.command.plot.*` as part of the criteria aswell. 

So you need `towny.command.plot.*` and `player.spawn.rpgbanknpc` to spawn banknpc.

Then allow server admin to set the banknpc's default skin. 

That's all.

**Comment by SirCraftypants** [comment]
So then ad server admin, i give both permissions to town mayors and permission to use the command to summon the banknpc.

**Comment by SirCraftypants** [comment]
So if i'm correct you only need to hook into Citizens2 and Vault as you're only using a Towny permission.

**Comment by SirCraftypants** [comment]
So it would basically be.

`towny.command.plot.*` and `player.spawn.rpgbanknpc` required for player to have access to command

`/rpgbank spawn townbank-1` & `/rpgbank delete townbank-1`

have a way where the spawned npc uses a preset config where the server admin can set the skin and other settings.

Then have the spawned/deleted bank npc save somewhere, be that in rpgbank or citizens.
