### ISSUE TITLE
[BUG?] Permission: rpgbank.user.max-pages.5 doesn't work

### ISSUE THREAD

**Issue by NeotenySS** [PluginBugs/Issues-RPGBank#12]
**Describe the bug**
So, I set the normal player rpgbank.user.max-pages.1
Then I set the permission rpgbank.user.max-pages.5 for the premium player, then using the command LuckPerms I gave the player a premium group.
Pre-set in config "max-pages: 5".
The problem is that for some reason the regular player has 5 pages at once, even if he has the permission rpgbank.user.max-pages.1

**To Reproduce**
1. Config set max-pages: 5
2. Give Premium player permission rpgbank.user.max-pages.5 (use LuckPerms)
3. Give normal player permission rpgbank.user.max-pages.1 (use LuckPerms)
4. See normal player have 5 slots... P.S.: It's as if the switch is just off

**Expected behavior**
Premium player has 5 pages, and a regular player has 1 page in the rpgbank

**Screenshots**
No errors in the console and no graphical errors, maybe permission just don't use this plugin?

**Info (please complete the following information):**
 - Spigot 1.19.2
 - Fabric 1.19.2
 - RPGBank 1.0.15

**Additional context**
I also do not see a command where you can call the admin menu, although in the screenshot is such a chip on the page Spigot

**Comment by LoneDev6** [comment]
I'll check this as soon as possible

**Comment by NeotenySS** [comment]
> I'll check this as soon as possible

Thanks, im waiting

**Comment by NeotenySS** [comment]
LuckPerms uses the parent function.
There are rights Test1 and they are given automatically to each player, he has rpgbank.user.max-pages.1

Then it gets the rights of Test2, which is the parent of Test2 and takes the functions from Test1 + gives those rights to Test2.
This way you don't have to rewrite a ton of perms.
That is, to solve the problem, I need in each branch of the rights to prescribe all perms and also disable the parent, so? It will take a long time, in other plugins, for example Auction, there rights prevail successfully
@LoneDev6

**Comment by LoneDev6** [comment]
I'll do some testing, probably the order of permissions is not correct.
I'll add support also for this case

**Comment by NeotenySS** [comment]
Thank you, please tell me when you will close the milestone and release an update? 
@LoneDev6
