### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Vaykhin** [PluginBugs/Issues-RPGBank#14]
Hello,
I just purchased and installed the plugin.
My server is on 1.19.3, but I haven't seen any warnings against this version.
With my players we are very often disconnected from the server at each first use of the plugin, at each connection, with this message:

`[16:46:30 INFO]: ArtasriveT lost connection: Internal Exception: io.netty.handler.codec.DecoderException: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled`

Do you have an idea ? 
Thank you

**Comment by LoneDev6** [comment]
Post the whole log
