### ISSUE TITLE
new Banker are counted as normal villager 

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-RPGBank#4]
When i spawn a banker i can use him normaly
All others too
Problem: he can be killed normaly like each villager

I know with a protected zone you can prevent attachs of villager...but thats not the issue... the issue is that u can kill them.
they should be immortals npcs xD

![Snag_15d842b6](https://user-images.githubusercontent.com/12080017/130687472-2c0384d2-5910-4ef2-b978-0790bd3e61f2.png)

RPGBank_1.0.14
LoneLibs_1.0.14

before the attack
![Snag_15db831c](https://user-images.githubusercontent.com/12080017/130687855-7a4bf05b-e892-4be8-8b2a-fc9cb09ca75c.png)

after the attack...
![Snag_15db4f1b](https://user-images.githubusercontent.com/12080017/130687824-cdc0d0fd-7f04-4a23-8705-b175c666edd6.png)

**Comment by LoneDev6** [comment]
Did you try to run `/rpgbank banker fix` ?

**Comment by CloudeLecaw** [comment]
I tried but without sucess

**Comment by LoneDev6** [comment]
If you're in creative it's normal, Minecraft allows you to kill entities even if they have the Invulnerable tag.
Can you confirm that you can't kill them in survival?

**Comment by CloudeLecaw** [comment]
Sorry for the late Feedback. Your right about the fake that it was just possible to kill thm in gm1. So the good point is that our players cant kill them.

Sobwe just habe one ittle more not for us so related problem, even if killed (means not existing anymore) there is no Option to bring them back, the only way is to spawn new once by command.
