### ISSUE TITLE
[BUG] Dupe: EXP Bottles giving increased amounts on each usage.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-RPGBank#6]
**Describe the bug**
Not getting the correct amount from the 

**To Reproduce**

give yourself the waterlogged sack and use the exp bottle, it should give you 100 exp, then repeatedly give another waterlooged sack and drink again and the amount will increase with each use.

**Expected behavior**
When saving a pre filled backpack named `waterlogged sack` with an EXP Bottle set as 100, upon using the EXP Bottle, it rewards 
100 exp on the first bottle as it should, then it give 200 on the second bottle, 300 on the third bottle, then 400 on the forth bottle when it should be consistently 100 every time?

So in 4 exp bottles i should end up with 400 exp but at present i'm ending up with 1000 exp.

[https://paste.helpch.at/dofoqusaqo.makefile](url)

 - Server version: Paper 1.18.1
 - Client version: Minecraft 1.18.1
 - RPG Bank version: 1.0.15
 - Epicbackpacks version: 1.3.12

I tried plugin reload and a few server restarts but it just won't work as it should be, bank cheques would as they should, it's just the exp bottles acting strangely.

**Comment by SirCraftypants** [comment]
The scoreboard plugin i'm using to track the exp increase as i drink the exp bottles is AnimatedScoreboard. https://www.spigotmc.org/resources/animatedscoreboard.20848/

**Comment by SirCraftypants** [comment]
Did some more testing and what it seems to be doing is, after drinking the first exp bottle, it doubles your exp balance with every exp bottle drunk.

**Comment by LoneDev6** [comment]
The exp is calculated with a specific formula to avoid duplications and wrong calculations.

# Each plugin represents exp in different ways:

## Vanilla
11 levels
![image](https://user-images.githubusercontent.com/27242001/211569284-3c6c47b3-b04b-4c8c-b23f-2402f1f60062.png)

## Essentials
70 units
![image](https://user-images.githubusercontent.com/27242001/211569250-3662b771-9338-4d65-b80d-c2e6f8f3cf84.png)

## `%player_total_exp%`
300 units
![image](https://user-images.githubusercontent.com/27242001/211569390-addbf485-f225-4bd8-ba7d-218ffcf55dd8.png)

## RPGBank
200 units
![image](https://user-images.githubusercontent.com/27242001/211569778-763055c9-2e96-4737-b224-c4a4c1975fd9.png)
![image](https://user-images.githubusercontent.com/27242001/211569797-e0f66e2d-ba67-4d0b-a4d8-cc2c077c084b.png)



# New feature

I now coded a new placeholder for you: `%rpgbank_player_exp%`
It shows the value RPGBank uses to represent the current player exp.

**Comment by SirCraftypants** [comment]
Appreciate the new placeholder but i don't understand how a placeholder fixes the exp bottle dupe where each time a bottle is duped it increases the reward of exp on each bottle being drunk.

There's no consistency, you set a bottle to give 10 exp, it should also give 10 exp.

**Comment by LoneDev6** [comment]
They do

https://user-images.githubusercontent.com/27242001/211590008-44ab3c77-81e4-46a8-af7d-42dae5ec2f0d.mp4

**Comment by SirCraftypants** [comment]
You're giving the exp bottles by command, the dupe occurs when you give set exp bottles inside ebp backpacks.
